services:
  - type: web
    name: zonastealer-bot
    env: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn bot:app
    envVars:
      - key: BOT_TOKEN
        value: 8364189800:AAHHsHHgKZ7oB6XSHExPWn0-0G5Fp8fGNi4
      - key: CHAT_ID
        value: "7725796090"
    plan: free
